// stdlib
#include <assert.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
// system
#include <arpa/inet.h>
#include <fcntl.h>
#include <netinet/ip.h>
#include <poll.h>
#include <sys/socket.h>
#include <unistd.h>
// C++
#include <string>
#include <vector>
// proj
#include "dlist.h"
#include "hashtable.h"
#include "zset.h"
#include <math.h>
#include <time.h>

using namespace std;
// A helpful alias so we don't have to type std::vector<uint8_t> over and over
typedef vector<uint8_t> Buffer;
enum {
  TAG_NIL = 0, // nil (like null)
  TAG_ERR = 1, // error code + msg
  TAG_STR = 2, // string
  TAG_INT = 3, // int64
  TAG_DBL = 4, // double
  TAG_ARR = 5, // array
};
// Macro to find the starting address of a struct, given the address of one of
// its members. This is heavily used in C (like in the Linux kernel) to simulate
// object-oriented inheritance. We use it here because the hashtable only knows
// about `HNode`, but we need to get back to our actual `Entry` struct that
// contains the string data.
#define container_of(ptr, T, member) ((T *)((char *)ptr - offsetof(T, member)))

// Get the current time in microseconds
static uint64_t get_monotonic_usec() {
  timespec tv = {0, 0};
  clock_gettime(CLOCK_MONOTONIC, &tv);
  return uint64_t(tv.tv_sec) * 1000000 + tv.tv_nsec / 1000;
}

static void msg(const char *msg) { fprintf(stderr, "%s\n", msg); }

static void msg_errno(const char *msg) {
  fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
  fprintf(stderr, "[%d] %s\n", errno, msg);
  abort();
}

static void fd_set_nb(int fd) {
  errno = 0;
  int flags = fcntl(fd, F_GETFL, 0);
  if (errno) {
    die("fcntl error");
    return;
  }

  flags |= O_NONBLOCK;

  errno = 0;
  (void)fcntl(fd, F_SETFL, flags);
  if (errno) {
    die("fcntl error");
  }
}

const size_t k_max_msg = 32 << 20; // likely larger than the kernel buffer

struct Conn {
  int fd = -1;
  // application's intention, for the event loop
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;
  // buffered input and output
  vector<uint8_t> incoming; // data to be parsed by the application
  vector<uint8_t> outgoing; // responses generated by the application
  uint64_t idle_start = 0;  // The exact microsecond this client connected
  struct DList idle_node;
};
// The massive Global Line where active connections wait
static struct DList g_idle_list;

// Helper function to renew a connection's timer
static void conn_put_idle(Conn *conn) {
  conn->idle_start = get_monotonic_usec();
  dlist_detach(&conn->idle_node); // remove from current position (if any)
  dlist_insert_before(
      &g_idle_list, &conn->idle_node); // put them at the very back of the line
}

const uint64_t k_idle_timeout_ms = 5 * 1000; // 5 seconds

// Calculate how long until the NEXT timer expires
static uint32_t next_timer_ms() {
  if (dlist_empty(&g_idle_list)) {
    return 10000; // default to 10s if nobody is connected
  }
  uint64_t now_us = get_monotonic_usec();
  Conn *next =
      container_of(g_idle_list.next, Conn,
                   idle_node); // Check the guy at the FRONT of the line
  uint64_t next_us = next->idle_start + k_idle_timeout_ms * 1000;
  if (next_us <= now_us) {
    return 0; // The timer has already expired! Wake up instantly.
  }
  return (uint32_t)((next_us - now_us) / 1000);
}

// The Grim Reaper: Check if anyone's timer has expired, and close their
// connection!
static void process_timers() {
  uint64_t now_us = get_monotonic_usec();
  while (!dlist_empty(&g_idle_list)) {
    Conn *next = container_of(g_idle_list.next, Conn, idle_node);
    uint64_t next_us = next->idle_start + k_idle_timeout_ms * 1000;
    if (next_us >= now_us + 1000) {
      break; // The guy at the front of the line isn't expired yet. Everyone
             // else is safe. Stop here!
    }
    printf("removing idle connection: %d\n", next->fd);
    next->want_close = true;        // Mark the connection for deletion
    dlist_detach(&next->idle_node); // Remove them from the timer line so we
                                    // don't process them again
  }
}

// append to the back
static void buf_append(vector<uint8_t> &buf, const uint8_t *data, size_t len) {
  buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(vector<uint8_t> &buf, size_t n) {
  buf.erase(buf.begin(), buf.begin() + n);
}
// --- BEGIN TLV SERIALIZATION HELPERS ---

static void buf_append_u8(Buffer &buf, uint8_t data) { buf.push_back(data); }
static void buf_append_u32(Buffer &buf, uint32_t data) {
  buf_append(buf, (const uint8_t *)&data, 4); // assume little-endian
}
static void buf_append_i64(Buffer &buf, int64_t data) {
  buf_append(buf, (const uint8_t *)&data, 8); // assume little-endian
}

// Write a NULL/NIL value
static void out_nil(Buffer &out) { buf_append_u8(out, TAG_NIL); }

// Write a String
static void out_str(Buffer &out, const string &val) {
  buf_append_u8(out, TAG_STR);
  buf_append_u32(out, (uint32_t)val.size());
  buf_append(out, (const uint8_t *)val.data(), val.size());
}

// Write a 64-bit Integer
static void out_int(Buffer &out, int64_t val) {
  buf_append_u8(out, TAG_INT);
  buf_append_i64(out, val);
}

// Write an Error
static void out_err(Buffer &out, int32_t code, const string &msg) {
  buf_append_u8(out, TAG_ERR);
  buf_append_u32(out, (uint32_t)code);
  buf_append_u32(out, (uint32_t)msg.size());
  buf_append(out, (const uint8_t *)msg.data(), msg.size());
}

// Write an Array (just the header, you loop to write items later)
static void out_arr(Buffer &out, uint32_t n) {
  buf_append_u8(out, TAG_ARR);
  buf_append_u32(out, n);
}
// --- END TLV SERIALIZATION HELPERS ---

// application callback when the listening socket is ready
static Conn *handle_accept(int fd) {
  // accept
  struct sockaddr_in client_addr = {};
  socklen_t addrlen = sizeof(client_addr);
  int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
  if (connfd < 0) {
    msg_errno("accept() error");
    return NULL;
  }
  uint32_t ip = client_addr.sin_addr.s_addr;
  fprintf(stderr, "new client from %u.%u.%u.%u:%u\n", ip & 255, (ip >> 8) & 255,
          (ip >> 16) & 255, ip >> 24, ntohs(client_addr.sin_port));

  // set the new connection fd to nonblocking mode
  fd_set_nb(connfd);

  // create a `struct Conn`
  Conn *conn = new Conn();
  conn->fd = connfd;
  conn->want_read = true;
  d_list_init(&conn->idle_node); // Initialize the ticket
  conn_put_idle(conn);           // Put them in line!
  return conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) {
  if (cur + 4 > end) {
    return false;
  }
  memcpy(&out, cur, 4);
  cur += 4;
  return true;
}

static bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n,
                     string &out) {
  if (cur + n > end) {
    return false;
  }
  out.assign(cur, cur + n);
  cur += n;
  return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t parse_req(const uint8_t *data, size_t size,
                         vector<string> &out) {
  const uint8_t *end = data + size;
  uint32_t nstr = 0;
  if (!read_u32(data, end, nstr)) {
    return -1;
  }
  if (nstr > k_max_args) {
    return -1; // safety limit
  }

  while (out.size() < nstr) {
    uint32_t len = 0;
    if (!read_u32(data, end, len)) {
      return -1;
    }
    out.push_back(string());
    if (!read_str(data, end, len, out.back())) {
      return -1;
    }
  }
  if (data != end) {
    return -1; // trailing garbage
  }
  return 0;
}

// global states
static struct {
  HMap db; // top-level hashtable instead of std::map
} g_data;

enum {
  T_STR = 0,
  T_ZSET = 1,
};

// KV pair for the top-level hashtable.
struct Entry {
  struct HNode node; // hashtable node
  string key;
  string val;
  uint32_t type = 0;
  ZSet *zset = NULL;
};

// equality comparison for `struct Entry`
// The hashtable calls this when resolving hash collisions to see if the actual
// string keys match.
static bool entry_eq(HNode *lhs, HNode *rhs) {
  // Cast the raw HNode pointers back to our custom Entry struct pointers
  struct Entry *le = container_of(lhs, struct Entry, node);
  struct Entry *re = container_of(rhs, struct Entry, node);
  // Compare the actual C++ strings
  return le->key == re->key;
}

// FNV hash function. A fast, standard hashing algorithm to convert a string
// into an integer.
static uint64_t str_hash(const uint8_t *data, size_t len) {
  uint32_t h = 0x811C9DC5;
  for (size_t i = 0; i < len; i++) {
    h = (h + data[i]) * 0x01000193;
  }
  return h;
}

static bool str2dbl(const string &s, double &out) {
  char *endp = NULL;
  out = strtod(s.c_str(), &endp);
  return endp == s.c_str() + s.size() && !isnan(out);
}

static bool str2int(const string &s, int64_t &out) {
  char *endp = NULL;
  out = strtoll(s.c_str(), &endp, 10);
  return endp == s.c_str() + s.size();
}

static bool expect_zset(Buffer &out, string &s, Entry **ent) {
  Entry key;
  key.key.swap(s);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
  HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);
  if (!hnode) {
    out_nil(out);
    return false;
  }
  *ent = container_of(hnode, Entry, node);
  if ((*ent)->type != T_ZSET) {
    out_err(out, 400, "wrong type: expected zset");
    return false;
  }
  return true;
}

static void do_get(vector<string> &cmd, Buffer &out) {
  // We create a dummy `Entry` just for the lookup. We only populate its key and
  // hcode.
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable lookup. We pass the equality function so the hashtable knows how
  // to handle collisions.
  HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
  if (!node) {
    out_nil(out); // Not Found
    return;
  }

  // found! We use container_of to turn the raw HNode pointer back into an Entry
  // pointer, then grab `val`.
  Entry *ent = container_of(node, Entry, node);
  if (ent->type != T_STR) {
    out_err(out, 400, "wrong type");
    return;
  }
  const string &val = ent->val;
  assert(val.size() <= k_max_msg);
  out_str(out, val); // Copy value to response
}

static void do_set(vector<string> &cmd, Buffer &out) {
  // a dummy `Entry` just for the lookup
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable lookup
  HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
  if (node) {
    Entry *ent = container_of(node, Entry, node);
    if (ent->type != T_STR) {
      out_err(out, 400, "wrong type");
      return;
    }
    // Key already exists! Update the value in place using swap for performance.
    ent->val.swap(cmd[2]);
  } else {
    // Key does not exist. Allocate a brand new Entry pair on the heap.
    Entry *ent = new Entry();
    ent->key.swap(key.key);           // Move the key string in
    ent->node.hcode = key.node.hcode; // Save the pre-calculated hash
    ent->val.swap(cmd[2]);            // Move the value string in
    ent->type = T_STR;
    hm_insert(&g_data.db, &ent->node); // Insert into hashtable
  }
  out_nil(out);
}

static void do_del(vector<string> &cmd, Buffer &out) {
  // a dummy `Entry` just for the lookup
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable delete: removes the node from the hash buckets and returns it to
  // us
  HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
  if (node) {
    Entry *ent = container_of(node, Entry, node);
    if (ent->type == T_ZSET) {
      zset_dispose(ent->zset);
      delete ent->zset;
    }
    delete ent;
    out_int(out, 1); // 1 means success
  } else {
    out_int(out, 0); // 0 means failure
  }
}
static bool cb_keys(HNode *node, void *arg) {
  Buffer &out = *(Buffer *)arg;
  const string &key = container_of(node, Entry, node)->key;
  out_str(out, key);
  return true;
}

static void do_keys(vector<string> &cmd, Buffer &out) {
  // Write the Array Tag and the Total Length
  out_arr(out, (uint32_t)hm_size(&g_data.db));
  // Tell the hashtable to run `cb_keys` on every single node!
  hm_foreach(&g_data.db, &cb_keys, (void *)&out);
}

static void do_zadd(vector<string> &cmd, Buffer &out) {
  double score = 0;
  if (!str2dbl(cmd[2], score)) {
    out_err(out, 400, "expect fp number");
    return;
  }

  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
  HNode *hnode = hm_lookup(&g_data.db, &key.node, &entry_eq);

  Entry *ent = NULL;
  if (!hnode) {
    ent = new Entry();
    ent->key.swap(key.key);
    ent->node.hcode = key.node.hcode;
    ent->type = T_ZSET;
    ent->zset = new ZSet();
    hm_insert(&g_data.db, &ent->node);
  } else {
    ent = container_of(hnode, Entry, node);
    if (ent->type != T_ZSET) {
      out_err(out, 400, "wrong type");
      return;
    }
  }

  const string &name = cmd[3];
  bool added = zset_add(ent->zset, name.data(), name.size(), score);
  out_int(out, (int64_t)added);
}

static void do_zrem(vector<string> &cmd, Buffer &out) {
  Entry *ent = NULL;
  if (!expect_zset(out, cmd[1], &ent)) {
    return;
  }

  const string &name = cmd[2];
  ZNode *znode = zset_pop(ent->zset, name.data(), name.size());
  if (znode) {
    delete znode;
    out_int(out, 1);
  } else {
    out_int(out, 0);
  }
}

static void do_zscore(vector<string> &cmd, Buffer &out) {
  Entry *ent = NULL;
  if (!expect_zset(out, cmd[1], &ent)) {
    return;
  }

  const string &name = cmd[2];
  ZNode *znode = zset_lookup(ent->zset, name.data(), name.size());
  if (znode) {
    out_str(out, to_string(znode->score));
  } else {
    out_nil(out);
  }
}

static void do_zquery(vector<string> &cmd, Buffer &out) {
  double score = 0;
  if (!str2dbl(cmd[2], score)) {
    out_err(out, 400, "expect fp number");
    return;
  }
  const string &name = cmd[3];
  int64_t offset = 0;
  int64_t limit = 0;
  if (!str2int(cmd[4], offset)) {
    out_err(out, 400, "expect int");
    return;
  }
  if (!str2int(cmd[5], limit)) {
    out_err(out, 400, "expect int");
    return;
  }

  Entry *ent = NULL;
  if (!expect_zset(out, cmd[1], &ent)) {
    if (out.back() == TAG_NIL) { // doesn't exist, return empty array
      out.pop_back();
      out_arr(out, 0);
    }
    return;
  }

  ZNode *znode = zset_query(ent->zset, score, name.data(), name.size(), offset);

  // We output an array of strings (name, score, name, score...)
  // But we need to write the array length first. We'll reserve space and fix it
  // later.
  size_t arr_len_pos = out.size();
  out_arr(out, 0);

  uint32_t count = 0;
  while (znode && count < (uint32_t)limit) {
    out_str(out, znode->name);
    out_str(out, to_string(znode->score));

    // move to the next node by using offset 1
    AVLNode *next_node = avl_offset(&znode->tree_node, 1);
    znode = next_node ? container_of(next_node, ZNode, tree_node) : NULL;
    count += 2; // We wrote 2 items (name and score)
  }
  // Update the array length!
  uint32_t network_count = count;
  memcpy(&out[arr_len_pos + 1], &network_count, 4);
}

static void do_request(vector<string> &cmd, Buffer &out) {
  if (cmd.size() == 2 && cmd[0] == "get") {
    return do_get(cmd, out);
  } else if (cmd.size() == 3 && cmd[0] == "set") {
    return do_set(cmd, out);
  } else if (cmd.size() == 2 && cmd[0] == "del") {
    return do_del(cmd, out);
  } else if (cmd.size() == 1 && cmd[0] == "keys") {
    return do_keys(cmd, out);
  } else if (cmd.size() == 4 && cmd[0] == "zadd") {
    return do_zadd(cmd, out);
  } else if (cmd.size() == 3 && cmd[0] == "zrem") {
    return do_zrem(cmd, out);
  } else if (cmd.size() == 3 && cmd[0] == "zscore") {
    return do_zscore(cmd, out);
  } else if (cmd.size() == 6 && cmd[0] == "zquery") {
    return do_zquery(cmd, out);
  } else {
    out_err(out, 400, "bad command");
  }
}
static void response_begin(Buffer &out, size_t *header) {
  *header = out.size();   // Remember where the header started
  buf_append_u32(out, 0); // Reserve 4 bytes of space with zeros
}

static size_t response_size(Buffer &out, size_t header) {
  return out.size() - header - 4; // Calculate how many bytes do_request added
}

static void response_end(Buffer &out, size_t header) {
  size_t msg_size = response_size(out, header);
  if (msg_size > k_max_msg) {
    out.resize(header + 4); // Oops, too big. Erase what do_request wrote.
    out_err(out, 2, "response is too big.");
    msg_size = response_size(out, header);
  }
  // Go back to the reserved space and write the real length!
  uint32_t len = (uint32_t)msg_size;
  memcpy(&out[header], &len, 4);
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
  // try to parse the protocol: message header
  if (conn->incoming.size() < 4) {
    return false; // want read
  }
  uint32_t len = 0;
  memcpy(&len, conn->incoming.data(), 4);
  if (len > k_max_msg) {
    msg("too long");
    conn->want_close = true;
    return false; // want close
  }
  // message body
  if (4 + len > conn->incoming.size()) {
    return false; // want read
  }
  const uint8_t *request = &conn->incoming[4];

  // got one request, do some application logic
  vector<string> cmd;
  if (parse_req(request, len, cmd) < 0) {
    msg("bad request");
    conn->want_close = true;
    return false; // want close
  }
  size_t header_pos = 0;
  response_begin(conn->outgoing, &header_pos);
  do_request(cmd, conn->outgoing);
  response_end(conn->outgoing, header_pos);

  // application logic done! remove the request message.
  buf_consume(conn->incoming, 4 + len);
  // Q: Why not just empty the buffer? See the explanation of "pipelining".
  return true; // success
}

// application callback when the socket is writable
static void handle_write(Conn *conn) {
  conn_put_idle(conn); // Renew the timer!
  assert(conn->outgoing.size() > 0);
  ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
  if (rv < 0 && errno == EAGAIN) {
    return; // actually not ready
  }
  if (rv < 0) {
    msg_errno("write() error");
    conn->want_close = true; // error handling
    return;
  }

  // remove written data from `outgoing`
  buf_consume(conn->outgoing, (size_t)rv);

  // update the readiness intention
  if (conn->outgoing.size() == 0) { // all data written
    conn->want_read = true;
    conn->want_write = false;
  } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
  conn_put_idle(conn); // Renew the timer!
  // read some data
  uint8_t buf[64 * 1024];
  ssize_t rv = read(conn->fd, buf, sizeof(buf));
  if (rv < 0 && errno == EAGAIN) {
    return; // actually not ready
  }
  // handle IO error
  if (rv < 0) {
    msg_errno("read() error");
    conn->want_close = true;
    return; // want close
  }
  // handle EOF
  if (rv == 0) {
    if (conn->incoming.size() == 0) {
      msg("client closed");
    } else {
      msg("unexpected EOF");
    }
    conn->want_close = true;
    return; // want close
  }
  // got some new data
  buf_append(conn->incoming, buf, (size_t)rv);

  // parse requests and generate responses
  while (try_one_request(conn)) {
  }
  // Q: Why calling this in a loop? See the explanation of "pipelining".

  // update the readiness intention
  if (conn->outgoing.size() > 0) { // has a response
    conn->want_read = false;
    conn->want_write = true;
    // The socket is likely ready to write in a request-response protocol,
    // try to write it without waiting for the next iteration.
    return handle_write(conn);
  } // else: want read
}

int main() {
  // the listening socket
  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    die("socket()");
  }
  int val = 1;
  setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

  // bind
  struct sockaddr_in addr = {};
  addr.sin_family = AF_INET;
  addr.sin_port = ntohs(1234);
  addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0
  int rv = bind(fd, (const sockaddr *)&addr, sizeof(addr));
  if (rv) {
    die("bind()");
  }

  // set the listen fd to nonblocking mode
  fd_set_nb(fd);

  // listen
  rv = listen(fd, SOMAXCONN);
  if (rv) {
    die("listen()");
  }

  // a map of all client connections, keyed by fd
  vector<Conn *> fd2conn;

  // Initialize the global timer line
  d_list_init(&g_idle_list);

  // the event loop
  vector<struct pollfd> poll_args;
  while (true) {
    // prepare the arguments of the poll()
    poll_args.clear();
    // put the listening sockets in the first position
    struct pollfd pfd = {fd, POLLIN, 0};
    poll_args.push_back(pfd);
    // the rest are connection sockets
    for (Conn *conn : fd2conn) {
      if (!conn) {
        continue;
      }
      // always poll() for error
      struct pollfd pfd = {conn->fd, POLLERR, 0};
      // poll() flags from the application's intent
      if (conn->want_read) {
        pfd.events |= POLLIN;
      }
      if (conn->want_write) {
        pfd.events |= POLLOUT;
      }
      poll_args.push_back(pfd);
    }

    // wait for readiness
    int timeout_ms = (int)next_timer_ms();
    int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), timeout_ms);
    if (rv < 0 && errno == EINTR) {
      continue; // not an error
    }
    if (rv < 0) {
      die("poll");
    }

    // The Grim Reaper strikes every time the event loop wakes up!
    process_timers();

    // handle the listening socket
    if (poll_args[0].revents) {
      if (Conn *conn = handle_accept(fd)) {
        // put it into the map
        if (fd2conn.size() <= (size_t)conn->fd) {
          fd2conn.resize(conn->fd + 1);
        }
        assert(!fd2conn[conn->fd]);
        fd2conn[conn->fd] = conn;
      }
    }

    // handle connection sockets
    for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
      uint32_t ready = poll_args[i].revents;
      if (ready == 0) {
        continue;
      }

      Conn *conn = fd2conn[poll_args[i].fd];
      if (ready & POLLIN) {
        assert(conn->want_read);
        handle_read(conn); // application logic
      }
      if (ready & POLLOUT) {
        assert(conn->want_write);
        handle_write(conn); // application logic
      }

      // close the socket from socket error or application logic
      if ((ready & POLLERR) || conn->want_close) {
        (void)close(conn->fd);
        dlist_detach(&conn->idle_node); // Remove from the timer line!
        fd2conn[conn->fd] = NULL;
        delete conn;
      }
    } // for each connection sockets
  } // the event loop
  return 0;
}