// stdlib
#include <assert.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
// system
#include <arpa/inet.h>
#include <fcntl.h>
#include <netinet/ip.h>
#include <poll.h>
#include <sys/socket.h>
#include <unistd.h>
// C++
#include <string>
#include <vector>
// proj
#include "hashtable.h"

using namespace std;
// A helpful alias so we don't have to type std::vector<uint8_t> over and over
typedef vector<uint8_t> Buffer;
enum {
  TAG_NIL = 0, // nil (like null)
  TAG_ERR = 1, // error code + msg
  TAG_STR = 2, // string
  TAG_INT = 3, // int64
  TAG_DBL = 4, // double
  TAG_ARR = 5, // array
};
// Macro to find the starting address of a struct, given the address of one of
// its members. This is heavily used in C (like in the Linux kernel) to simulate
// object-oriented inheritance. We use it here because the hashtable only knows
// about `HNode`, but we need to get back to our actual `Entry` struct that
// contains the string data.
#define container_of(ptr, T, member) ((T *)((char *)ptr - offsetof(T, member)))

static void msg(const char *msg) { fprintf(stderr, "%s\n", msg); }

static void msg_errno(const char *msg) {
  fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
  fprintf(stderr, "[%d] %s\n", errno, msg);
  abort();
}

static void fd_set_nb(int fd) {
  errno = 0;
  int flags = fcntl(fd, F_GETFL, 0);
  if (errno) {
    die("fcntl error");
    return;
  }

  flags |= O_NONBLOCK;

  errno = 0;
  (void)fcntl(fd, F_SETFL, flags);
  if (errno) {
    die("fcntl error");
  }
}

const size_t k_max_msg = 32 << 20; // likely larger than the kernel buffer

struct Conn {
  int fd = -1;
  // application's intention, for the event loop
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;
  // buffered input and output
  vector<uint8_t> incoming; // data to be parsed by the application
  vector<uint8_t> outgoing; // responses generated by the application
};

// append to the back
static void buf_append(vector<uint8_t> &buf, const uint8_t *data, size_t len) {
  buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(vector<uint8_t> &buf, size_t n) {
  buf.erase(buf.begin(), buf.begin() + n);
}
// --- BEGIN TLV SERIALIZATION HELPERS ---

static void buf_append_u8(Buffer &buf, uint8_t data) { buf.push_back(data); }
static void buf_append_u32(Buffer &buf, uint32_t data) {
  buf_append(buf, (const uint8_t *)&data, 4); // assume little-endian
}
static void buf_append_i64(Buffer &buf, int64_t data) {
  buf_append(buf, (const uint8_t *)&data, 8); // assume little-endian
}

// Write a NULL/NIL value
static void out_nil(Buffer &out) { buf_append_u8(out, TAG_NIL); }

// Write a String
static void out_str(Buffer &out, const string &val) {
  buf_append_u8(out, TAG_STR);
  buf_append_u32(out, (uint32_t)val.size());
  buf_append(out, (const uint8_t *)val.data(), val.size());
}

// Write a 64-bit Integer
static void out_int(Buffer &out, int64_t val) {
  buf_append_u8(out, TAG_INT);
  buf_append_i64(out, val);
}

// Write an Error
static void out_err(Buffer &out, int32_t code, const string &msg) {
  buf_append_u8(out, TAG_ERR);
  buf_append_u32(out, (uint32_t)code);
  buf_append_u32(out, (uint32_t)msg.size());
  buf_append(out, (const uint8_t *)msg.data(), msg.size());
}

// Write an Array (just the header, you loop to write items later)
static void out_arr(Buffer &out, uint32_t n) {
  buf_append_u8(out, TAG_ARR);
  buf_append_u32(out, n);
}
// --- END TLV SERIALIZATION HELPERS ---

// application callback when the listening socket is ready
static Conn *handle_accept(int fd) {
  // accept
  struct sockaddr_in client_addr = {};
  socklen_t addrlen = sizeof(client_addr);
  int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
  if (connfd < 0) {
    msg_errno("accept() error");
    return NULL;
  }
  uint32_t ip = client_addr.sin_addr.s_addr;
  fprintf(stderr, "new client from %u.%u.%u.%u:%u\n", ip & 255, (ip >> 8) & 255,
          (ip >> 16) & 255, ip >> 24, ntohs(client_addr.sin_port));

  // set the new connection fd to nonblocking mode
  fd_set_nb(connfd);

  // create a `struct Conn`
  Conn *conn = new Conn();
  conn->fd = connfd;
  conn->want_read = true;
  return conn;
}

const size_t k_max_args = 200 * 1000;

static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out) {
  if (cur + 4 > end) {
    return false;
  }
  memcpy(&out, cur, 4);
  cur += 4;
  return true;
}

static bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n,
                     string &out) {
  if (cur + n > end) {
    return false;
  }
  out.assign(cur, cur + n);
  cur += n;
  return true;
}

// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+

static int32_t parse_req(const uint8_t *data, size_t size,
                         vector<string> &out) {
  const uint8_t *end = data + size;
  uint32_t nstr = 0;
  if (!read_u32(data, end, nstr)) {
    return -1;
  }
  if (nstr > k_max_args) {
    return -1; // safety limit
  }

  while (out.size() < nstr) {
    uint32_t len = 0;
    if (!read_u32(data, end, len)) {
      return -1;
    }
    out.push_back(string());
    if (!read_str(data, end, len, out.back())) {
      return -1;
    }
  }
  if (data != end) {
    return -1; // trailing garbage
  }
  return 0;
}

// global states
static struct {
  HMap db; // top-level hashtable instead of std::map
} g_data;

// KV pair for the top-level hashtable.
// We embed the `HNode` struct directly inside our Entry struct.
// This is an "intrusive" data structure. The hashtable algorithm only sees
// `node`, but using the `container_of` macro, we can get back to the `key` and
// `val`.
struct Entry {
  struct HNode node; // hashtable node
  string key;
  string val;
};

// equality comparison for `struct Entry`
// The hashtable calls this when resolving hash collisions to see if the actual
// string keys match.
static bool entry_eq(HNode *lhs, HNode *rhs) {
  // Cast the raw HNode pointers back to our custom Entry struct pointers
  struct Entry *le = container_of(lhs, struct Entry, node);
  struct Entry *re = container_of(rhs, struct Entry, node);
  // Compare the actual C++ strings
  return le->key == re->key;
}

// FNV hash function. A fast, standard hashing algorithm to convert a string
// into an integer.
static uint64_t str_hash(const uint8_t *data, size_t len) {
  uint32_t h = 0x811C9DC5;
  for (size_t i = 0; i < len; i++) {
    h = (h + data[i]) * 0x01000193;
  }
  return h;
}

static void do_get(vector<string> &cmd, Response &out) {
  // We create a dummy `Entry` just for the lookup. We only populate its key and
  // hcode.
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable lookup. We pass the equality function so the hashtable knows how
  // to handle collisions.
  HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
  if (!node) {
    out.status = RES_NX; // Not Found
    return;
  }

  // found! We use container_of to turn the raw HNode pointer back into an Entry
  // pointer, then grab `val`.
  const string &val = container_of(node, Entry, node)->val;
  assert(val.size() <= k_max_msg);
  out.data.assign(val.begin(), val.end()); // Copy value to response
}

static void do_set(vector<string> &cmd, Response &) {
  // a dummy `Entry` just for the lookup
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable lookup
  HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
  if (node) {
    // Key already exists! Update the value in place using swap for performance.
    container_of(node, Entry, node)->val.swap(cmd[2]);
  } else {
    // Key does not exist. Allocate a brand new Entry pair on the heap.
    Entry *ent = new Entry();
    ent->key.swap(key.key);            // Move the key string in
    ent->node.hcode = key.node.hcode;  // Save the pre-calculated hash
    ent->val.swap(cmd[2]);             // Move the value string in
    hm_insert(&g_data.db, &ent->node); // Insert into hashtable
  }
}

static void do_del(vector<string> &cmd, Response &) {
  // a dummy `Entry` just for the lookup
  Entry key;
  key.key.swap(cmd[1]);
  key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());

  // hashtable delete: removes the node from the hash buckets and returns it to
  // us
  HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
  if (node) {
    // It's our responsibility to actually free the memory!
    delete container_of(node, Entry, node);
  }
}

static void do_request(vector<string> &cmd, Response &out) {
  if (cmd.size() == 2 && cmd[0] == "get") {
    return do_get(cmd, out);
  } else if (cmd.size() == 3 && cmd[0] == "set") {
    return do_set(cmd, out);
  } else if (cmd.size() == 2 && cmd[0] == "del") {
    return do_del(cmd, out);
  } else {
    out.status = RES_ERR; // unrecognized command
  }
}

static void make_response(const Response &resp, vector<uint8_t> &out) {
  uint32_t resp_len = 4 + (uint32_t)resp.data.size();
  buf_append(out, (const uint8_t *)&resp_len, 4);
  buf_append(out, (const uint8_t *)&resp.status, 4);
  buf_append(out, resp.data.data(), resp.data.size());
}

// process 1 request if there is enough data
static bool try_one_request(Conn *conn) {
  // try to parse the protocol: message header
  if (conn->incoming.size() < 4) {
    return false; // want read
  }
  uint32_t len = 0;
  memcpy(&len, conn->incoming.data(), 4);
  if (len > k_max_msg) {
    msg("too long");
    conn->want_close = true;
    return false; // want close
  }
  // message body
  if (4 + len > conn->incoming.size()) {
    return false; // want read
  }
  const uint8_t *request = &conn->incoming[4];

  // got one request, do some application logic
  vector<string> cmd;
  if (parse_req(request, len, cmd) < 0) {
    msg("bad request");
    conn->want_close = true;
    return false; // want close
  }
  Response resp;
  do_request(cmd, resp);
  make_response(resp, conn->outgoing);

  // application logic done! remove the request message.
  buf_consume(conn->incoming, 4 + len);
  // Q: Why not just empty the buffer? See the explanation of "pipelining".
  return true; // success
}

// application callback when the socket is writable
static void handle_write(Conn *conn) {
  assert(conn->outgoing.size() > 0);
  ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
  if (rv < 0 && errno == EAGAIN) {
    return; // actually not ready
  }
  if (rv < 0) {
    msg_errno("write() error");
    conn->want_close = true; // error handling
    return;
  }

  // remove written data from `outgoing`
  buf_consume(conn->outgoing, (size_t)rv);

  // update the readiness intention
  if (conn->outgoing.size() == 0) { // all data written
    conn->want_read = true;
    conn->want_write = false;
  } // else: want write
}

// application callback when the socket is readable
static void handle_read(Conn *conn) {
  // read some data
  uint8_t buf[64 * 1024];
  ssize_t rv = read(conn->fd, buf, sizeof(buf));
  if (rv < 0 && errno == EAGAIN) {
    return; // actually not ready
  }
  // handle IO error
  if (rv < 0) {
    msg_errno("read() error");
    conn->want_close = true;
    return; // want close
  }
  // handle EOF
  if (rv == 0) {
    if (conn->incoming.size() == 0) {
      msg("client closed");
    } else {
      msg("unexpected EOF");
    }
    conn->want_close = true;
    return; // want close
  }
  // got some new data
  buf_append(conn->incoming, buf, (size_t)rv);

  // parse requests and generate responses
  while (try_one_request(conn)) {
  }
  // Q: Why calling this in a loop? See the explanation of "pipelining".

  // update the readiness intention
  if (conn->outgoing.size() > 0) { // has a response
    conn->want_read = false;
    conn->want_write = true;
    // The socket is likely ready to write in a request-response protocol,
    // try to write it without waiting for the next iteration.
    return handle_write(conn);
  } // else: want read
}

int main() {
  // the listening socket
  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    die("socket()");
  }
  int val = 1;
  setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

  // bind
  struct sockaddr_in addr = {};
  addr.sin_family = AF_INET;
  addr.sin_port = ntohs(1234);
  addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0
  int rv = bind(fd, (const sockaddr *)&addr, sizeof(addr));
  if (rv) {
    die("bind()");
  }

  // set the listen fd to nonblocking mode
  fd_set_nb(fd);

  // listen
  rv = listen(fd, SOMAXCONN);
  if (rv) {
    die("listen()");
  }

  // a map of all client connections, keyed by fd
  vector<Conn *> fd2conn;
  // the event loop
  vector<struct pollfd> poll_args;
  while (true) {
    // prepare the arguments of the poll()
    poll_args.clear();
    // put the listening sockets in the first position
    struct pollfd pfd = {fd, POLLIN, 0};
    poll_args.push_back(pfd);
    // the rest are connection sockets
    for (Conn *conn : fd2conn) {
      if (!conn) {
        continue;
      }
      // always poll() for error
      struct pollfd pfd = {conn->fd, POLLERR, 0};
      // poll() flags from the application's intent
      if (conn->want_read) {
        pfd.events |= POLLIN;
      }
      if (conn->want_write) {
        pfd.events |= POLLOUT;
      }
      poll_args.push_back(pfd);
    }

    // wait for readiness
    int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
    if (rv < 0 && errno == EINTR) {
      continue; // not an error
    }
    if (rv < 0) {
      die("poll");
    }

    // handle the listening socket
    if (poll_args[0].revents) {
      if (Conn *conn = handle_accept(fd)) {
        // put it into the map
        if (fd2conn.size() <= (size_t)conn->fd) {
          fd2conn.resize(conn->fd + 1);
        }
        assert(!fd2conn[conn->fd]);
        fd2conn[conn->fd] = conn;
      }
    }

    // handle connection sockets
    for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
      uint32_t ready = poll_args[i].revents;
      if (ready == 0) {
        continue;
      }

      Conn *conn = fd2conn[poll_args[i].fd];
      if (ready & POLLIN) {
        assert(conn->want_read);
        handle_read(conn); // application logic
      }
      if (ready & POLLOUT) {
        assert(conn->want_write);
        handle_write(conn); // application logic
      }

      // close the socket from socket error or application logic
      if ((ready & POLLERR) || conn->want_close) {
        (void)close(conn->fd);
        fd2conn[conn->fd] = NULL;
        delete conn;
      }
    } // for each connection sockets
  } // the event loop
  return 0;
}